# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) * np.array(Y)
 
print(result)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


### 3. Write a Python Program to Transpose a Matrix?

In [4]:
import numpy as np
A = np.array([[1, 2], [5,6]])
A_T = A.transpose()
print(A_T)

[[1 5]
 [2 6]]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [6]:
my_str = input("Enter a string: ")  
# breakdown the string into a list of words  
words = my_str.split()  
# sort the list  
words.sort()  
# display the sorted words  
for word in words:  
   print(word)  

Enter a string: a b C d I A
A
C
I
a
b
d


### 5. Write a Python Program to Remove Punctuation From a String?

In [7]:
test_str = "Hey, Hi!!, I am a student of FSDA Batch in Ineuron!!"

print("The original string is : " + test_str)
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~''' #initialize the punctuation string
 
for ele in test_str:
    if ele in punc:
        test_str = test_str.replace(ele, "") #replacing the punctuation sign 
 
# printing result
print("The string after punctuation filter : " + test_str)

The original string is : Hey, Hi!!, I am a student of FSDA Batch in Ineuron!!
The string after punctuation filter : Hey Hi I am a student of FSDA Batch in Ineuron
